# Generated by Django 3.2.18 on 2023-04-28 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.category'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=models.TextField(),
        ),
    ]
