# Generated by Django 3.2.18 on 2023-04-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230428_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='icon',
            field=models.CharField(default='computer', max_length=255),
        ),
    ]
