# Generated by Django 4.1.7 on 2023-04-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_faculty_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='icon',
        ),
    ]
